-- No-op migration.
-- The knowledge engine schema was already created in
-- 20260505170145_init, so replaying the original SQL here caused
-- duplicate enum/table creation failures in Prisma shadow databases.
